name: MineRaiders
version: 1.0
author: YaoGuai
main: MR
api-version: 1.21
commands:
  mineraidersdebug:
    description: debug command
    aliases:
      - mrd
      - mrdebug
    usage: /mineraidersdebug [index]
  loots:
    description: get all loots
    usage: /loots
  gadgets:
    description: get all gadgets
    usage: /gadgets